"use client";

import Link from "next/link";
import { ArrowRight, Bot, MapPin, ShieldCheck, Users } from "lucide-react";
import { PublicHeader } from "@/components/nivaran/brand";
import { useLanguage } from "@/components/nivaran/language-provider";
import { Button } from "@/components/ui/button";

const copy={
  en:{eyebrow:"Community redressal, without the runaround",title:"Raise it once. See who owns it.",body:"Report a local issue by typing or speaking. Nivaran groups repeat complaints, recommends urgency, and keeps a human reviewer responsible for the final routing.",cta:"Open resident workspace",points:["Readable location, not raw coordinates","Shared incidents without exposing residents","Human approval before department assignment"]},
  hi:{eyebrow:"सीधी और जवाबदेह नागरिक शिकायत",title:"एक बार बताइए। जिम्मेदारी साफ़ देखिए।",body:"स्थानीय समस्या लिखकर या बोलकर दर्ज करें। निवारण दोहराई गई शिकायतों को जोड़ता है, प्राथमिकता सुझाता है और अंतिम विभाग चयन की जिम्मेदारी मानव समीक्षक के पास रखता है।",cta:"निवासी कार्यक्षेत्र खोलें",points:["निर्देशांक नहीं, पढ़ने योग्य स्थान","पहचान बताए बिना साझा समस्या","विभाग भेजने से पहले मानव मंज़ूरी"]},
  mr:{eyebrow:"सरळ आणि जबाबदार नागरी तक्रार",title:"एकदा सांगा. जबाबदारी स्पष्ट पाहा.",body:"स्थानिक समस्या लिहून किंवा बोलून नोंदवा. निवारण पुनरावृत्तीच्या तक्रारी एकत्र करते, प्राधान्य सुचवते आणि अंतिम विभाग निवडीची जबाबदारी मानवी तपासकाकडे ठेवते.",cta:"नागरिक कार्यक्षेत्र उघडा",points:["अक्षांश-रेखांशाऐवजी वाचनीय पत्ता","ओळख न उघडता सामायिक घटना","विभागाकडे पाठवण्यापूर्वी मानवी मंजुरी"]},
};

export default function Home(){const {locale}=useLanguage();const c=copy[locale];return <main><PublicHeader/><section className="paper-grid border-b"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-20 lg:grid-cols-[1.1fr_.9fr] lg:px-10 lg:py-28"><div><p className="eyebrow">{c.eyebrow}</p><h1 className="display mt-5 max-w-3xl text-5xl sm:text-6xl">{c.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{c.body}</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link href="/resident">{c.cta}<ArrowRight/></Link></Button><Button asChild size="lg" variant="outline"><Link href="/login">Sign in</Link></Button></div></div><aside className="self-center border bg-card p-6"><p className="text-sm font-bold">What residents can expect</p><div className="mt-5 space-y-4">{c.points.map((point,index)=>{const Icon=[MapPin,Users,ShieldCheck][index];return <div key={point} className="flex items-start gap-3 border-t pt-4 first:border-0 first:pt-0"><Icon className="mt-0.5 size-5 text-civic"/><span className="text-sm leading-6">{point}</span></div>})}</div><div className="mt-6 flex items-start gap-3 bg-civic/5 p-4"><Bot className="mt-0.5 size-5 text-civic"/><p className="text-sm leading-6">The filing assistant asks only for complaint details and submits only after confirmation.</p></div></aside></div></section><footer className="mx-auto flex max-w-6xl flex-wrap justify-between gap-3 px-5 py-7 text-xs text-muted-foreground lg:px-10"><span><b className="text-foreground">Nivaran</b> · Synthetic civic operations prototype</span><span>No municipality partnership is implied.</span></footer></main>}
