"use client";

import Link from "next/link";
import { ArrowRight,FileText,Gauge,Languages,Route,ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PublicHeader,TrustStrip } from "@/components/nivaran/brand";
import { RoutingWorkspace } from "@/components/nivaran/routing-workspace";
import { useLanguage } from "@/components/nivaran/language-provider";

export default function Home(){const {t}=useLanguage();const steps=[1,2,3,4].map((number)=>({number:`0${number}`,title:t(`step${number}Title` as "step1Title"),copy:t(`step${number}Copy` as "step1Copy")}));const features=[{icon:Languages,title:t("feature1"),copy:t("feature1Copy")},{icon:Route,title:t("feature2"),copy:t("feature2Copy")},{icon:Gauge,title:t("feature3"),copy:t("feature3Copy")},{icon:FileText,title:t("feature4"),copy:t("feature4Copy")}];return <main><PublicHeader/><section className="paper-grid border-b"><div className="mx-auto grid max-w-[1440px] gap-12 px-5 py-16 lg:grid-cols-[.78fr_1.22fr] lg:px-10 lg:py-24"><div className="self-center"><p className="eyebrow">{t("heroEyebrow")}</p><h1 className="display mt-5 max-w-3xl text-5xl sm:text-6xl xl:text-7xl">{t("heroTitle")}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">{t("heroCopy")}</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link href="/resident/report">{t("report")} <ArrowRight/></Link></Button><Button asChild variant="outline" size="lg"><Link href="/login">{t("residentSignIn")}</Link></Button></div><p className="mt-5 flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4 text-civic"/>{t("emergency")}</p></div><div className="relative"><div className="absolute -top-4 right-8 z-10 bg-ink px-3 py-2 font-mono text-[10px] font-bold uppercase tracking-wider text-white">Real product workspace</div><RoutingWorkspace interactive={false}/></div></div></section><TrustStrip/><section className="mx-auto max-w-[1440px] px-5 py-20 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.6fr_1.4fr]"><div><p className="eyebrow">{t("handoffEyebrow")}</p><h2 className="mt-4 text-4xl font-bold tracking-[-.045em]">{t("handoffTitle")}</h2><p className="mt-5 leading-7 text-muted-foreground">{t("handoffCopy")}</p></div><div className="grid border-l border-t sm:grid-cols-2">{steps.map((step)=><article key={step.number} className="min-h-48 border-r border-b p-6"><span className="font-mono text-xs font-bold text-civic">{step.number}</span><h3 className="mt-8 text-xl font-bold tracking-[-.03em]">{step.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{step.copy}</p></article>)}</div></div></section><section className="bg-ink text-white"><div className="mx-auto grid max-w-[1440px] gap-px bg-white/15 lg:grid-cols-4">{features.map(({icon:Icon,title,copy})=><div key={title} className="bg-ink p-8"><Icon className="size-5 text-emerald-300"/><h3 className="mt-8 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-white/65">{copy}</p></div>)}</div></section><footer className="border-t"><div className="mx-auto flex max-w-[1440px] flex-wrap items-center justify-between gap-4 px-5 py-8 text-xs text-muted-foreground lg:px-10"><span><b className="text-foreground">Nivaran</b> · {t("synthetic")}</span><span>{t("noClaims")}</span></div></footer></main>}
