"use client";
import { useEffect, useState } from "react";
import { Loader2, ShieldAlert } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { MetricCard } from "./metric-card";
type Data = { open_complaints: number; resolved_complaints: number; active_breaches: number; sla_compliance: number; categories: { name: string; value: number }[]; wards: { name: string; value: number }[] };
export function AdminDashboard() {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState("");
  async function load() { setError(""); try { const response = await api<{ data: Data }>("/admin/dashboard"); setData(response.data); } catch (caught) { setError(caught instanceof Error ? caught.message : "Dashboard unavailable"); } }
  useEffect(() => { api<{ data: Data }>("/admin/dashboard").then((response) => setData(response.data)).catch((caught) => setError(caught instanceof Error ? caught.message : "Dashboard unavailable")); }, []);
  if (!data && !error) return <div className="grid min-h-72 place-items-center border bg-card"><Loader2 className="animate-spin text-civic" /></div>;
  if (!data) return <div className="border border-red-200 bg-red-50 p-5 text-sm text-red-900"><b>Operational data could not be loaded.</b><p className="mt-2">{error}</p><Button variant="outline" className="mt-4" onClick={load}>Try again</Button></div>;
  return <div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Open complaints" value={data.open_complaints} note="Persisted active records" /><MetricCard label="SLA compliance" value={`${data.sla_compliance}%`} note="Calculated from SLA records" /><MetricCard label="Active breaches" value={data.active_breaches} note="Persisted breach events" attention={data.active_breaches > 0} /><MetricCard label="Resolved" value={data.resolved_complaints} note="Committed resolutions" /></div><div className="mt-7 grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><section className="border bg-card p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">Operational health</p><h2 className="mt-2 text-xl font-bold">Complaint mix</h2></div><Badge variant="outline">Persisted categories</Badge></div>{data.categories.length ? <div className="mt-6 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.categories}><CartesianGrid vertical={false} strokeDasharray="3 3" /><XAxis dataKey="name" tickLine={false} axisLine={false} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} /><Tooltip /><Bar dataKey="value" fill="var(--civic)" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></div> : <p className="grid h-72 place-items-center text-sm text-muted-foreground">No complaints have been categorized yet.</p>}</section><aside className={`border p-5 ${data.active_breaches ? "border-amber-300 bg-amber-50/45" : "bg-card"}`}><ShieldAlert className="size-5 text-amber-800" /><p className="eyebrow mt-4">SLA evaluator</p><h2 className="mt-3 text-xl font-bold">{data.active_breaches ? `${data.active_breaches} active breach${data.active_breaches === 1 ? "" : "es"}` : "No active breaches"}</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">This count comes directly from persisted SLA records. Open the SLA command center for the underlying complaints.</p></aside></div></div>;
}
