"use client";
import { useEffect, useState } from "react";
import { AlertTriangle, Clock3, FlaskConical, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { api, Complaint } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
type Row = { complaint: Complaint; sla: { risk_score: number; breached_at?: string; resolution_due_at: string; escalation_level: number } };
export function EscalationCenter() {
  const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [running, setRunning] = useState<string>(); const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { const response = await api<{ data: Row[] }>("/admin/escalations"); setRows(response.data); } catch (caught) { setError(caught instanceof Error ? caught.message : "Escalations unavailable"); } finally { setLoading(false); } }
  useEffect(() => { api<{ data: Row[] }>("/admin/escalations").then((response) => setRows(response.data)).catch((caught) => setError(caught instanceof Error ? caught.message : "Escalations unavailable")).finally(() => setLoading(false)); }, []);
  async function simulate(id: string) { setRunning(id); try { await api(`/admin/escalations/${id}/simulate`, { method: "POST" }); toast.success("Breach processed through SLA, notification, and audit workflows"); await load(); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Simulation failed"); } finally { setRunning(undefined); } }
  return <div><div><p className="eyebrow">Controlled evaluator capability</p><h2 className="mt-2 text-3xl font-bold tracking-[-.04em]">SLA command center</h2><p className="mt-2 text-sm text-muted-foreground">Only persisted at-risk or breached service windows appear here.</p></div>{loading ? <div className="mt-7 grid min-h-48 place-items-center border bg-card"><Loader2 className="animate-spin text-civic" /></div> : error ? <p className="mt-7 border border-red-200 bg-red-50 p-4 text-sm text-red-900">{error}</p> : !rows.length ? <p className="mt-7 border bg-card p-8 text-center text-sm text-muted-foreground">No service windows are currently at risk.</p> : <div className="mt-7 divide-y border bg-card">{rows.map(({ complaint, sla }) => <article key={complaint.id} className="grid items-center gap-4 p-5 md:grid-cols-[1.1fr_.65fr_.55fr_auto]"><div><div className="flex items-center gap-2"><AlertTriangle className="size-4 text-amber-800" /><b className="font-mono text-sm">{complaint.reference_number}</b></div><p className="mt-2 text-sm">{complaint.title || complaint.normalized_text || complaint.category}</p></div><div><span className="text-xs text-muted-foreground">SLA state</span><b className="mt-1 flex items-center gap-1 text-sm"><Clock3 className="size-3" />{sla.breached_at ? `Breached · level ${sla.escalation_level}` : `Risk ${Math.round(sla.risk_score * 100)}%`}</b></div><Badge variant={sla.breached_at ? "destructive" : "outline"}>{complaint.status.replaceAll("_", " ")}</Badge><Button onClick={() => simulate(complaint.id)} disabled={Boolean(running) || Boolean(sla.breached_at)}><FlaskConical />{running === complaint.id ? "Running…" : sla.breached_at ? "Processed" : "Simulate breach"}</Button></article>)}</div>}</div>;
}
