"use client";
import { createContext, useContext, useEffect, useMemo, useState } from "react";
export type Locale = "en" | "hi" | "mr";
const en = {
  signIn:"Sign in",lite:"Lite mode",sms:"SMS simulator",report:"Report an issue",residentSignIn:"Resident sign in",heroEyebrow:"Samanvay Nagar · Public service prototype",heroTitle:"A complaint should never disappear between departments.",heroCopy:"Nivaran turns multilingual resident reports into privacy-safe, accountable civic work—while people remain responsible for every consequential decision.",emergency:"For emergencies, contact your local emergency service.",handoffEyebrow:"The accountable handoff",handoffTitle:"From an everyday report to visible responsibility.",handoffCopy:"Know who owns the next step, why they own it, and what happens when time runs out.",step1Title:"Report in your words",step1Copy:"Type, speak, use Lite mode, or use the SMS simulator without knowing the department.",step2Title:"Protect before processing",step2Copy:"Service teams receive privacy-safe operational text, not unnecessary identity details.",step3Title:"Human approval before routing",step3Copy:"AI recommends urgency and eligible services; a reviewer must approve or change the decision before assignment.",step4Title:"Follow every handoff",step4Copy:"Assignments, delays, escalations, and resolutions appear in your private timeline.",feature1:"Three-language intake",feature1Copy:"Complete resident journeys in English, Hindi, and Marathi, including code-switched complaints.",feature2:"Rule-grounded routing",feature2Copy:"AI can recommend only departments allowed by configured service rules.",feature3:"Shared local incidents",feature3Copy:"Nearby reports about the same asset are clubbed without exposing resident identities.",feature4:"Traceable decisions",feature4Copy:"Important changes retain the actor, reason, time, and previous value.",synthetic:"Synthetic civic operations prototype",noClaims:"No municipality partnership or adoption claim is implied.",loginRole:"Choose a civic role",loginTitle:"One system. Four accountable views.",loginSeed:"These local demo accounts use real API-enforced permissions.",email:"Email",password:"Password",continueAs:"Continue as",checking:"Checking access…",loginIntro:"Credentials are prefilled for this local demonstration.",trackEyebrow:"Private resident tracking",trackTitle:"Your complaints, visible only after sign-in.",trackCopy:"References, responsible services, updates, and review paths stay inside your resident account.",reportEyebrow:"Resident service",reportTitle:"Tell us what needs attention.",reportCopy:"Type or speak in your language, attach evidence, and use GPS when you choose.",myComplaints:"My complaints",newIssue:"Report new issue",preferences:"Preferences",signOut:"Sign out",notifications:"In-app notifications",fullSite:"Full site",liteTitle:"Low-bandwidth report",liteCopy:"Text first. No map or analytics bundle. Add evidence later if needed.",smsTitle:"Civic service in a familiar conversation.",smsCopy:"This simulator supports guidance, clarification, and private status messages. It sends no telecom message."
} as const;
type MessageKey = keyof typeof en;
const hi: Record<MessageKey,string> = {
  signIn:"साइन इन",lite:"लाइट मोड",sms:"SMS सिम्युलेटर",report:"समस्या दर्ज करें",residentSignIn:"निवासी साइन इन",heroEyebrow:"समन्वय नगर · सार्वजनिक सेवा प्रोटोटाइप",heroTitle:"शिकायत विभागों के बीच कभी गायब नहीं होनी चाहिए।",heroCopy:"निवारण बहुभाषी निवासी शिकायतों को गोपनीयता-सुरक्षित और जवाबदेह नागरिक कार्य में बदलता है—हर महत्वपूर्ण निर्णय की जिम्मेदारी इंसानों के पास रहती है।",emergency:"आपात स्थिति में स्थानीय आपात सेवा से संपर्क करें।",handoffEyebrow:"जवाबदेह हस्तांतरण",handoffTitle:"रोज़मर्रा की शिकायत से स्पष्ट जिम्मेदारी तक।",handoffCopy:"जानें अगला कदम किसका है, क्यों है और समय सीमा चूकने पर क्या होगा।",step1Title:"अपने शब्दों में बताएं",step1Copy:"विभाग जाने बिना लिखें, बोलें, लाइट मोड या SMS सिम्युलेटर इस्तेमाल करें।",step2Title:"प्रसंस्करण से पहले सुरक्षा",step2Copy:"सेवा टीमों को केवल गोपनीयता-सुरक्षित कार्य संबंधी जानकारी मिलती है।",step3Title:"रूटिंग से पहले मानवीय मंज़ूरी",step3Copy:"AI तात्कालिकता और योग्य सेवाएं सुझाता है; असाइनमेंट से पहले समीक्षक की मंज़ूरी या बदलाव जरूरी है।",step4Title:"हर हस्तांतरण देखें",step4Copy:"असाइनमेंट, देरी, एस्केलेशन और समाधान आपकी निजी समयरेखा में दिखते हैं।",feature1:"तीन भाषाओं में सेवा",feature1Copy:"अंग्रेज़ी, हिंदी और मराठी में पूर्ण निवासी अनुभव, मिली-जुली भाषा सहित।",feature2:"नियम-आधारित रूटिंग",feature2Copy:"AI केवल कॉन्फ़िगर किए गए सेवा नियमों से अनुमत विभाग सुझा सकता है।",feature3:"साझा स्थानीय घटनाएं",feature3Copy:"एक ही स्थान की शिकायतें निवासी पहचान बताए बिना एक घटना में जोड़ी जाती हैं।",feature4:"निर्णयों का रिकॉर्ड",feature4Copy:"महत्वपूर्ण बदलावों में व्यक्ति, कारण, समय और पिछला मान सुरक्षित रहता है।",synthetic:"कृत्रिम नागरिक संचालन प्रोटोटाइप",noClaims:"किसी नगरपालिका साझेदारी या उपयोग का दावा नहीं है।",loginRole:"नागरिक भूमिका चुनें",loginTitle:"एक व्यवस्था। चार जवाबदेह दृश्य।",loginSeed:"इन स्थानीय डेमो खातों की अनुमतियां API पर वास्तव में लागू हैं।",email:"ईमेल",password:"पासवर्ड",continueAs:"आगे बढ़ें",checking:"पहुंच जांची जा रही है…",loginIntro:"स्थानीय प्रदर्शन के लिए विवरण पहले से भरे हैं।",trackEyebrow:"निजी शिकायत स्थिति",trackTitle:"आपकी शिकायतें केवल साइन इन के बाद।",trackCopy:"संदर्भ, जिम्मेदार सेवाएं, अपडेट और समीक्षा विकल्प आपके निजी खाते में रहते हैं।",reportEyebrow:"निवासी सेवा",reportTitle:"बताएं कहाँ ध्यान देने की जरूरत है।",reportCopy:"अपनी भाषा में लिखें या बोलें, प्रमाण जोड़ें और चाहें तो GPS इस्तेमाल करें।",myComplaints:"मेरी शिकायतें",newIssue:"नई समस्या दर्ज करें",preferences:"प्राथमिकताएं",signOut:"साइन आउट",notifications:"ऐप में सूचनाएं",fullSite:"पूरी साइट",liteTitle:"कम डेटा वाली शिकायत",liteCopy:"पहले टेक्स्ट। नक्शा या एनालिटिक्स बंडल नहीं। प्रमाण बाद में जोड़ें।",smsTitle:"परिचित बातचीत में नागरिक सेवा।",smsCopy:"यह सिम्युलेटर मार्गदर्शन, स्पष्टीकरण और निजी स्थिति संदेश देता है। कोई टेलीकॉम संदेश नहीं भेजता।"
};
const mr: Record<MessageKey,string> = {
  signIn:"साइन इन",lite:"लाइट मोड",sms:"SMS सिम्युलेटर",report:"समस्या नोंदवा",residentSignIn:"नागरिक साइन इन",heroEyebrow:"समन्वय नगर · सार्वजनिक सेवा नमुना",heroTitle:"तक्रार विभागांमध्ये कधीही हरवू नये.",heroCopy:"निवारण बहुभाषिक नागरिक तक्रारींचे गोपनीयता-सुरक्षित आणि जबाबदार नागरी कामात रूपांतर करते—प्रत्येक महत्त्वाच्या निर्णयाची जबाबदारी माणसांकडेच राहते.",emergency:"आपत्कालीन परिस्थितीत स्थानिक आपत्कालीन सेवेशी संपर्क साधा.",handoffEyebrow:"जबाबदार हस्तांतरण",handoffTitle:"दैनंदिन तक्रारीपासून स्पष्ट जबाबदारीपर्यंत.",handoffCopy:"पुढील पाऊल कोणाचे, का आणि मुदत चुकल्यास काय होईल ते जाणून घ्या.",step1Title:"तुमच्या शब्दांत सांगा",step1Copy:"विभाग माहित नसतानाही लिहा, बोला, लाइट मोड किंवा SMS सिम्युलेटर वापरा.",step2Title:"प्रक्रियेपूर्वी संरक्षण",step2Copy:"सेवा पथकाला फक्त गोपनीयता-सुरक्षित कामाशी संबंधित मजकूर मिळतो.",step3Title:"मार्गनियुक्तीपूर्वी मानवी मंजुरी",step3Copy:"AI तातडी आणि पात्र सेवा सुचवते; नियुक्तीपूर्वी तपासकाची मंजुरी किंवा बदल आवश्यक आहे.",step4Title:"प्रत्येक हस्तांतरण पाहा",step4Copy:"नियुक्ती, विलंब, एस्कलेशन आणि निराकरण तुमच्या खासगी कालरेषेत दिसते.",feature1:"तीन भाषांतील सेवा",feature1Copy:"इंग्रजी, हिंदी आणि मराठीतील संपूर्ण नागरिक अनुभव, मिश्र भाषेसह.",feature2:"नियमाधारित मार्गनियुक्ती",feature2Copy:"AI फक्त कॉन्फिगर केलेल्या सेवा नियमांनी मंजूर विभाग सुचवू शकते.",feature3:"सामायिक स्थानिक घटना",feature3Copy:"एकाच ठिकाणच्या तक्रारी नागरिकांची ओळख न दाखवता एका घटनेत जोडल्या जातात.",feature4:"निर्णयांचा मागोवा",feature4Copy:"महत्त्वाच्या बदलांसाठी व्यक्ती, कारण, वेळ आणि मागील मूल्य जतन होते.",synthetic:"कृत्रिम नागरी कार्यप्रणाली नमुना",noClaims:"कोणत्याही महानगरपालिका भागीदारीचा किंवा वापराचा दावा नाही.",loginRole:"नागरी भूमिका निवडा",loginTitle:"एक व्यवस्था. चार जबाबदार दृश्ये.",loginSeed:"या स्थानिक डेमो खात्यांच्या परवानग्या API वर खरोखर लागू होतात.",email:"ईमेल",password:"पासवर्ड",continueAs:"पुढे जा",checking:"प्रवेश तपासत आहोत…",loginIntro:"स्थानिक प्रात्यक्षिकासाठी तपशील आधीच भरले आहेत.",trackEyebrow:"खासगी तक्रार मागोवा",trackTitle:"तुमच्या तक्रारी फक्त साइन इन केल्यानंतर.",trackCopy:"संदर्भ, जबाबदार सेवा, अपडेट आणि पुनरावलोकन पर्याय तुमच्या खासगी खात्यात राहतात.",reportEyebrow:"नागरिक सेवा",reportTitle:"कशाकडे लक्ष देण्याची गरज आहे ते सांगा.",reportCopy:"तुमच्या भाषेत लिहा किंवा बोला, पुरावा जोडा आणि हवे असल्यास GPS वापरा.",myComplaints:"माझ्या तक्रारी",newIssue:"नवीन समस्या नोंदवा",preferences:"प्राधान्ये",signOut:"साइन आउट",notifications:"अ‍ॅपमधील सूचना",fullSite:"संपूर्ण साइट",liteTitle:"कमी डेटामधील तक्रार",liteCopy:"आधी मजकूर. नकाशा किंवा विश्लेषण बंडल नाही. पुरावा नंतर जोडा.",smsTitle:"ओळखीच्या संभाषणातून नागरी सेवा.",smsCopy:"हा सिम्युलेटर मार्गदर्शन, स्पष्टीकरण आणि खासगी स्थिती संदेश देतो. दूरसंचार संदेश पाठवत नाही."
};
const messages: Record<Locale,Record<MessageKey,string>> = { en, hi, mr };
const LanguageContext = createContext<{locale:Locale;setLocale:(locale:Locale)=>void;t:(key:MessageKey)=>string}>({ locale:"en", setLocale:()=>{}, t:(key)=>en[key] });
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocale] = useState<Locale>("en");
  useEffect(() => { const timer = setTimeout(() => { const saved = localStorage.getItem("nivaran-locale"); if (saved === "hi" || saved === "mr") setLocale(saved); }, 0); return () => clearTimeout(timer); }, []);
  useEffect(() => { document.documentElement.lang = locale; localStorage.setItem("nivaran-locale", locale); }, [locale]);
  const value = useMemo(() => ({ locale, setLocale, t: (key: MessageKey) => messages[locale][key] }), [locale]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
export function useLanguage() { return useContext(LanguageContext); }
