"use client";

import { useState } from "react";
import { Send,Signal,Smartphone } from "lucide-react";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useLanguage } from "./language-provider";

type Message={from:"resident"|"nivaran";text:string};
const copy={en:{intro:"NIVARAN: Describe the civic issue in your language. Status is available only for complaints in your signed-in account.",placeholder:"Type your report…",offline:"Network unavailable. Your typed message remains visible; retry when connected.",notice:"Simulator only · No telecom message is sent"},hi:{intro:"निवारण: अपनी भाषा में नागरिक समस्या बताएं। स्थिति केवल आपके साइन-इन खाते की शिकायतों के लिए उपलब्ध है।",placeholder:"अपनी शिकायत लिखें…",offline:"नेटवर्क उपलब्ध नहीं है। आपका लिखा संदेश यहीं रहेगा; कनेक्शन आने पर फिर कोशिश करें।",notice:"केवल सिम्युलेटर · कोई टेलीकॉम संदेश नहीं भेजा जाता"},mr:{intro:"निवारण: तुमच्या भाषेत नागरी समस्या सांगा. स्थिती फक्त तुमच्या साइन-इन खात्यातील तक्रारींसाठी उपलब्ध आहे.",placeholder:"तुमची तक्रार लिहा…",offline:"नेटवर्क उपलब्ध नाही. तुमचा मजकूर इथेच राहील; जोडणी झाल्यावर पुन्हा प्रयत्न करा.",notice:"फक्त सिम्युलेटर · दूरसंचार संदेश पाठवला जात नाही"}} as const;

export function SmsTerminal(){const {locale}=useLanguage();const c=copy[locale];const [session,setSession]=useState<string>();const [messages,setMessages]=useState<Message[]>([]);const [busy,setBusy]=useState(false);async function send(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const input=new FormData(form).get("message")?.toString().trim();if(!input)return;setMessages((current)=>[...current,{from:"resident",text:input}]);form.reset();setBusy(true);try{const response=await api<{data:{session_id:string;reply:string}}>("/sms-simulator/message",{method:"POST",body:JSON.stringify({session_id:session,message:input,language:locale})});setSession(response.data.session_id);setMessages((current)=>[...current,{from:"nivaran",text:response.data.reply}])}catch{setMessages((current)=>[...current,{from:"nivaran",text:c.offline}])}finally{setBusy(false)}}return <div className="mx-auto max-w-lg overflow-hidden border-8 border-ink bg-[#efeade] shadow-2xl"><div className="flex items-center justify-between bg-ink px-4 py-3 text-white"><span className="flex items-center gap-2 text-xs font-bold"><Smartphone className="size-4"/> NIVARAN / 60060</span><Signal className="size-4 text-emerald-300"/></div><div className="flex min-h-[430px] flex-col gap-3 p-4 font-mono text-sm"><div className="max-w-[88%] border border-stone-400 bg-white p-3 leading-6"><span className="mb-1 block text-[9px] font-bold uppercase tracking-wider opacity-60">nivaran</span>{c.intro}</div>{messages.map((message,index)=><div key={index} className={`max-w-[88%] border p-3 leading-6 ${message.from==="resident"?"ml-auto border-civic bg-civic text-white":"border-stone-400 bg-white"}`}><span className="mb-1 block text-[9px] font-bold uppercase tracking-wider opacity-60">{message.from}</span>{message.text}</div>)}</div><form onSubmit={send} className="flex gap-2 border-t bg-white p-3"><Input name="message" aria-label="SMS message" placeholder={c.placeholder} autoComplete="off"/><Button size="icon" disabled={busy} aria-label="Send message"><Send/></Button></form><div className="bg-secondary px-4 py-2 text-[10px] text-muted-foreground">{c.notice}</div></div>}
