"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, LockKeyhole } from "lucide-react";
import { api, Complaint } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useLanguage } from "./language-provider";
const status = { en:{submitted:"Safely received",processing:"Being understood",awaiting_review:"Awaiting human review",assigned:"Sent to service teams",acknowledged:"Acknowledged",in_progress:"Work underway",escalated:"Escalated",resolved:"Resolved",reopened:"Review request open"}, hi:{submitted:"सुरक्षित रूप से प्राप्त",processing:"शिकायत समझी जा रही है",awaiting_review:"मानवीय समीक्षा बाकी",assigned:"सेवा टीमों को भेजी गई",acknowledged:"प्राप्ति स्वीकार हुई",in_progress:"काम जारी है",escalated:"पर्यवेक्षक को भेजी गई",resolved:"समाधान पूरा",reopened:"पुनः समीक्षा जारी"}, mr:{submitted:"सुरक्षितपणे प्राप्त",processing:"तक्रार समजून घेत आहोत",awaiting_review:"मानवी तपासणी बाकी",assigned:"सेवा पथकाकडे पाठवली",acknowledged:"स्वीकृती मिळाली",in_progress:"काम सुरू आहे",escalated:"पर्यवेक्षकाकडे पाठवली",resolved:"निराकरण झाले",reopened:"पुनर्तपासणी सुरू"} } as const;
const text = { en:{loading:"Loading your private complaints…",error:"We could not load your account.",empty:"No complaints in this account",report:"Report an issue",stage:"Current stage",service:"Recommended service",approval:"Reviewer gate",open:"Open private timeline"}, hi:{loading:"आपकी निजी शिकायतें लोड हो रही हैं…",error:"आपका खाता लोड नहीं हो सका।",empty:"इस खाते में कोई शिकायत नहीं है",report:"समस्या दर्ज करें",stage:"वर्तमान चरण",service:"सुझाई गई सेवा",approval:"समीक्षक मंज़ूरी",open:"निजी समयरेखा खोलें"}, mr:{loading:"तुमच्या खासगी तक्रारी लोड होत आहेत…",error:"तुमचे खाते लोड झाले नाही.",empty:"या खात्यात तक्रारी नाहीत",report:"समस्या नोंदवा",stage:"सध्याचा टप्पा",service:"सुचवलेली सेवा",approval:"तपासक मंजुरी",open:"खासगी कालरेषा उघडा"} } as const;
export function TrackForm() {
  const { locale, tr, status: statusLabel, category } = useLanguage(); const c = text[locale]; const [rows, setRows] = useState<Complaint[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { api<{ data: Complaint[] }>("/complaints").then((response) => setRows(response.data)).catch(() => setError(c.error)).finally(() => setLoading(false)); }, [c.error]);
  if (loading) return <div className="border bg-card p-8 text-sm text-muted-foreground">{c.loading}</div>;
  if (error) return <div role="alert" className="border border-red-200 bg-red-50 p-6 text-red-900"><b>{c.error}</b><p className="mt-2 text-sm">{error}</p><Button asChild className="mt-4"><Link href="/login">{tr("Sign in again")}</Link></Button></div>;
  if (!rows.length) return <div className="border bg-card p-8 text-center"><LockKeyhole className="mx-auto size-7 text-civic" /><h2 className="mt-4 text-xl font-bold">{c.empty}</h2><Button asChild className="mt-5"><Link href="/resident/report">{c.report}</Link></Button></div>;
  return <div className="space-y-4">{rows.map((complaint) => { const state = status[locale][complaint.status as keyof typeof status.en] || statusLabel(complaint.status); const display = locale === "hi" ? complaint.translation_hi || complaint.normalized_text || complaint.safe_text : locale === "mr" ? complaint.translation_mr || complaint.normalized_text || complaint.safe_text : complaint.normalized_text || complaint.safe_text; return <article key={complaint.id} className="border bg-card p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs font-bold text-civic">{complaint.reference_number}</p><h2 className="mt-2 text-xl font-bold">{display}</h2><p className="mt-1 text-sm text-muted-foreground">{complaint.location_text}</p></div><Badge>{state}</Badge></div><div className="mt-5 grid gap-px border bg-border sm:grid-cols-3"><div className="bg-card p-4"><span className="text-xs text-muted-foreground">{c.stage}</span><b className="mt-1 block">{state}</b></div><div className="bg-card p-4"><span className="text-xs text-muted-foreground">{c.service}</span><b className="mt-1 block">{category(complaint.category)}</b></div><div className="bg-card p-4"><span className="text-xs text-muted-foreground">{c.approval}</span><b className="mt-1 block">{complaint.priority_reviewed ? tr("Approved") : tr("Required before assignment")}</b></div></div><Button asChild variant="outline" className="mt-5"><Link href={`/resident/complaints/${complaint.id}`}>{c.open} <ArrowRight /></Link></Button></article>; })}</div>;
}
